-- Liquibase SQL Changelog - Database Agnostic Version
-- Works with: H2 (dev), MySQL 8+ (prod), PostgreSQL

-- Users Table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    points INT DEFAULT 0 NOT NULL,
    parent_id BIGINT,
    CONSTRAINT CHK_users_role CHECK (role IN ('CHILD','PARENT'))
);

-- Children Table  
CREATE TABLE children (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    points INT DEFAULT 0 NOT NULL,
    parent_id BIGINT NOT NULL,
    CONSTRAINT CHK_children_role CHECK (role IN ('CHILD','PARENT')),
    CONSTRAINT FK_children_parent FOREIGN KEY (parent_id) REFERENCES users(id)
);

-- Tasks Table
CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    points INT NOT NULL,
    type VARCHAR(20) NOT NULL,
    status VARCHAR(20),
    active BOOLEAN DEFAULT TRUE NOT NULL,
    penalty_points INT,
    deadline_type VARCHAR(20),
    deadline_value INT,
    created_by_id BIGINT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME,
    CONSTRAINT CHK_tasks_type CHECK (type IN ('DAILY_ONCE','MANDATORY','ONE_TIME','REPEATABLE')),
    CONSTRAINT CHK_tasks_status CHECK (status IN ('APPROVED','DRAFT','REJECTED')),
    CONSTRAINT CHK_tasks_deadline_type CHECK (deadline_type IN ('DAILY','WEEKLY_TIMES'))
);

-- Task Jobs Table
CREATE TABLE task_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    child_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    snapshot_title VARCHAR(100) NOT NULL,
    snapshot_description VARCHAR(500),
    snapshot_points INT NOT NULL,
    snapshot_task_type VARCHAR(20) NOT NULL,
    assigned_at DATETIME NOT NULL,
    started_at DATETIME,
    deadline DATETIME,
    created_at DATETIME NOT NULL,
    updated_at DATETIME,
    CONSTRAINT CHK_task_jobs_status CHECK (status IN ('ASSIGNED','CANCELLED','COMPLETED','IN_PROGRESS')),
    CONSTRAINT CHK_task_jobs_type CHECK (snapshot_task_type IN ('DAILY_ONCE','MANDATORY','ONE_TIME','REPEATABLE'))
);

-- Task Completions Table
CREATE TABLE task_completions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    task_job_id BIGINT,
    child_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    proof VARCHAR(8000),
    completed_at DATETIME NOT NULL,
    approved_at DATETIME,
    CONSTRAINT CHK_completions_status CHECK (status IN ('APPROVED','PENDING','REJECTED'))
);

-- Rewards Table
CREATE TABLE rewards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    quantity INT DEFAULT 999 NOT NULL,
    points_required INT NOT NULL,
    image_url VARCHAR(500),
    active BOOLEAN DEFAULT TRUE NOT NULL
);

-- Reward Redemptions Table
CREATE TABLE reward_redemptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reward_id BIGINT NOT NULL,
    child_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    redeemed_at DATETIME NOT NULL,
    used_at DATETIME,
    note VARCHAR(500),
    CONSTRAINT CHK_redemptions_status CHECK (status IN ('REDEEMED','USED'))
);

-- Lottery Themes Table
CREATE TABLE lottery_themes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    points_per_draw INT NOT NULL,
    type VARCHAR(20) NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    created_by_id BIGINT NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME,
    CONSTRAINT CHK_themes_type CHECK (type IN ('FIXED_PROBABILITY','GUARANTEED','WEIGHTED_RANDOM'))
);

-- Lottery Prizes Table
CREATE TABLE lottery_prizes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lottery_theme_id BIGINT NOT NULL,
    reward_id BIGINT,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    image_url VARCHAR(500),
    weight INT NOT NULL,
    probability INT,
    quantity INT DEFAULT -1 NOT NULL,
    redeemed_count INT DEFAULT 0 NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME
);

-- Lottery Draws Table
CREATE TABLE lottery_draws (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lottery_theme_id BIGINT NOT NULL,
    child_id BIGINT NOT NULL,
    points_cost INT NOT NULL,
    result_status VARCHAR(20) NOT NULL,
    draw_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    CONSTRAINT CHK_draws_result CHECK (result_status IN ('JACKPOT','NO_WIN','WON'))
);

-- Lottery Draw Results Table
CREATE TABLE lottery_draw_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lottery_draw_id BIGINT NOT NULL,
    prize_id BIGINT NOT NULL,
    reward_id BIGINT,
    prize_name VARCHAR(100) NOT NULL,
    created_at DATETIME NOT NULL
);

-- Point History Table
CREATE TABLE point_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id BIGINT NOT NULL,
    change_type VARCHAR(30) NOT NULL,
    change_points INT NOT NULL,
    original_points INT NOT NULL,
    after_points INT NOT NULL,
    description VARCHAR(500),
    reference_id BIGINT,
    reference_type VARCHAR(50),
    changed_by_id BIGINT,
    created_at DATETIME NOT NULL,
    CONSTRAINT CHK_history_type CHECK (change_type IN ('BONUS','INITIAL','LOTTERY_DRAW','LOTTERY_WIN','MANUAL_ADJUSTMENT','OTHER','PENALTY','REWARD_REDEMPTION','TASK_COMPLETION'))
);

-- Penalty Rules Table
CREATE TABLE penalty_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    points INT NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    created_by_id BIGINT NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME
);

-- Penalty Records Table
CREATE TABLE penalty_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id BIGINT NOT NULL,
    penalty_rule_id BIGINT NOT NULL,
    points INT NOT NULL,
    note VARCHAR(500),
    applied_by_id BIGINT NOT NULL,
    applied_at DATETIME NOT NULL
);

-- Penalty Notifications Table
CREATE TABLE penalty_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id BIGINT NOT NULL,
    parent_id BIGINT NOT NULL,
    task_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    notification_time DATETIME NOT NULL,
    penalty_points INT,
    is_penalty_applied BOOLEAN,
    applied_by_id BIGINT,
    applied_at DATETIME,
    CONSTRAINT CHK_notifications_status CHECK (status IN ('APPLIED','DISMISSED','EXPIRED','PENDING'))
);
